language: node_js
node_js:
  - 8.11.4
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    branch: code-master
before_script:
  - yarn
script:
  - yarn build

